name: Count Lines of Code

on: 
  push:
    branches:
      - main

jobs:
  cloc:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install cloc
        run: |
          sudo apt-get update
          sudo apt-get install -y cloc

      - name: Run cloc
        run: |
          cloc --vcs git --out cloc_output.txt
          cat cloc_output.txt | grep SUM > line_stats.txt

      - name: Upload line stats
        uses: actions/upload-artifact@v2
        with:
          name: line-stats
          path: line_stats.txt
