name: Update README Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  push:
    branches:
      - main  # Change this to the branch you use if different

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Total Lines of Code
        run: |
          cloc --vcs git --out cloc_output.txt
          cat cloc_output.txt | grep SUM > line_stats.txt

      - name: Update README with Stats
        run: |
          LINES=$(cat line_stats.txt | awk '{print $5}')
          sed -i "s/<!-- LINES -->/${LINES}/" README.md

      - name: Commit Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add README.md
          git commit -m "Updated code stats"
          git push
